### PR TITLE
upstream: remove dependency on cfriedt/thrift and depend on apache/thrift directly

### PR DESCRIPTION
**Pull request by cfriedt**
This changeset actually has a fairly big impact - it removes the dependency on [cfriedt/thrift](https://github.com/cfriedt/thrift) (a fork) and enables the module to use [apache/thrift](https://github.com/apache/thrift) directly 😀

With that, we will also be able to pin to a specific release of [apache/thrift](https://github.com/apache/thrift), likely the upcoming v0.18.0 release.

The only remaining issue now is to fix `std::thread` and `std::mutex` in Zephyr. As a temporary workaround, we've copied in the affected apache/thrift sources and headers and made some slight modifications. Eventually, when Zephyr supports `std::thread` and `std::mutex`, we can remove those workarounds.

See individual commit messages for details.

### CODE REVIEW

**Comment by cfriedt** [comment]
Keeping this in draft, as it is blocked by
- [x] zephyrproject-rtos/zephyr#52313
- [x] zephyrproject-rtos/zephyr#52316
- [x] zephyrproject-rtos/zephyr#51771

**Comment by cfriedt** [comment]
* temporarily added a commit to build this PR against zephyrproject-rtos/zephyr#51771
* once zephyrproject-rtos/zephyr#51771 is merged to Zephyr `main`, the temporary commit can be removed and this PR can be merged here
* at that point, we are mostly ready to upstream

**Comment by cfriedt** [comment]
Need to update git submodule commit after apache/thrift#2745 is merged, as it appears that TSocketServer.cpp (upstream) leaks file descriptors.

For more details, see 
https://issues.apache.org/jira/browse/THRIFT-5677

cc @stephanosio @SdtElectronics 

Young, you may have encountered this in your SSL work.

**Comment by cfriedt** [comment]
> Need to update git submodule commit after [apache/thrift#2745](https://github.com/apache/thrift/pull/2745) is merged, as it appears that TSocketServer.cpp (upstream) leaks file descriptors.

I was wrong - it seems that custom deleters are not working in Zephyr's C++ runtime. If that were the case, then `destroyer_of_fine_sockets()` would be called.

https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/transport/TServerSocket.cpp#L91
https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/transport/TServerSocket.cpp#L407

Kind of an interesting C++ quirk @stephanosio. Might be good to add a test for that. I'm sure it's a lot more involved under the hood, of course ;-)

**Comment by cfriedt** [comment]
It looks like both the file descriptor leak and the memory leak might have been my fault 😝 . I commented-out the `delete pClient` that triggered cleanup, which was itself just a workaround for the warning / error generated due to the non-virtual destructor of `TConnectedClient`.

**Comment by cfriedt** [comment]
@stephanosio - once this is green (which I hope it will be shortly), we should be ok to merge
- zephyrproject-rtos/zephyr#51771
- drop commit 96f692f2547a05701812a6ac3836d3d8db270bfb after the above PR is merged into Zephyr `main`
- merge this PR into `gsoc-2022-thrift/main`
- make a PR to add `apache/thrift` to Zephyr's `west.yml`, and merge the `tests/`, and `samples/`, `lib/` into `modules/lib/thrift/`, etc
- create some additional documentation with the above PR, likely with a walkthrough for qemu for each protocol / transport, as well as a board-specific walkthrough (esp32-c3?) that exercises e.g. Python compatibility on the host

**Comment by cfriedt** [comment]
* removed staging commit to build against Zephyr PR 51771 (so building against `main` again)

**Review by jeremybettis — APPROVED** [review]

**Comment by cfriedt** [comment]
IIRC Stephanos is off for the next couple of days, so opening this up to other reviewers.

**Review by SdtElectronics — APPROVED** [review]

**Pull request merged**
