### PR TITLE
remove west.yml

### PR DESCRIPTION
**Pull request by cfriedt**
This was required when the repo was organized as a "downstream" project. However, it has since been reworked to use submanifests.

That makes the `west.yml` file obsolete here, so remove it.

### CODE REVIEW

**Review by stephanosio — APPROVED** [review]

**Comment by cfriedt** [comment]
Weird - CI didn't run after this file was removed.. I'm skeptical.
Skeptical

**Comment by cfriedt** [comment]
@stephanosio - this is extremely sketchy. I rebased and for some reason, removing this file prevents CI from running. Any ideas?

**Comment by stephanosio** [comment]
> @stephanosio - this is extremely sketchy. For some reason, removing this file prevents CI from running. Any ideas? I even rebased onto main and updated this PR, which I thought would for sure trigger CI.

very strange indeed ... the workflows should have triggered for this PR.

can you try creating another PR?

**Comment by cfriedt** [comment]
> > @stephanosio - this is extremely sketchy. For some reason, removing this file prevents CI from running. Any ideas? I even rebased onto main and updated this PR, which I thought would for sure trigger CI.
> 
> very strange indeed ... the workflows should have triggered for this PR.
> 
> can you try creating another PR?

Yes, will do shortly

**Pull request merged**
